name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: UditAwasthi
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: push to output branch
        run: |
          git init output
          cd output
          git checkout -b output
          cp -r ../dist/. .
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update contribution snake [skip ci]"
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/UditAwasthi/UditAwasthi.git"
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
